version: "2"

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: musu
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  post:
    image: bruhski/mususocial:post
    container_name: post
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/post
      SPRING_DATASOURCE_USERNAME: 'musu'
      SPRING_DATASOURCE_PASSWORD: 'password'
    depends_on:
      - postgres

  user:
    image: bruhski/mususocial:user
    container_name: user
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/user
      SPRING_DATASOURCE_USERNAME: 'musu'
      SPRING_DATASOURCE_PASSWORD: 'password'
    depends_on:
      - postgres

  message:
    image: bruhski/mususocial:message
    container_name: message
    ports:
      - '8083:8083'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/message
      SPRING_DATASOURCE_USERNAME: 'musu'
      SPRING_DATASOURCE_PASSWORD: 'password'
    depends_on:
      - postgres

  frontend:
    image: bruhski/mususocial:frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  nodeserver:
    image: bruhski/mususocial:nodeserver
    container_name: nodeserver
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      
  vertx:
    image: bruhski/mususocial:vertx
    container_name: vertx
    ports:
      - '8084:8084'
    depends_on:
      - postgres 

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: