server:
  port: 8083

spring:
  application:
    name: post
  datasource:
    username: 'musu'
    url: jdbc:postgresql://localhost:5432/message
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true