
name: frontend CI docker

on:
  push:
    paths:
      - "Frontend/**"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: bruhski/mususocial
        tags: frontend
        registry: docker.io
        dockerfile: Frontend/Dockerfile
        directory: Frontend/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
