# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: User CI maven & docker

on:
  push:
    paths:
      - "Backend/User/**"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ./Backend/User/
      run: mvn -B package --file pom.xml
    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: bruhski/mususocial
        tags: user
        registry: docker.io
        dockerfile: Backend/User/Dockerfile
        directory: Backend/User/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
