
name: vertx CI docker

on:
  push:
    paths:
      - "Backend/Vertx/**"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: bruhski/mususocial
        tags: vertx
        registry: docker.io
        dockerfile: Backend/Vertx/Dockerfile
        directory: Backend/Vertx/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
